CREATE TABLE USERS (UID VARCHAR(10)PRIMARY KEY,UNAME VARCHAR(20));
CREATE TABLE PRODUCTS (PID VARCHAR(10) PRIMARY KEY,PNAME VARCHAR(20));
CREATE TABLE ORDERS (OID VARCHAR(20)PRIMARY KEY,UNAME VARCHAR(20),PID 
VARCHAR(10)REFERENCES PRODUCTS(PID),PNAME VARCHAR(20),PRICE 
INTEGER,QUANTITY INTEGER);
CREATE TABLE ORDER_DETAILS(OID VARCHAR(20) REFERENCES
ORDERS(OID),ODATE DATE,ADDRESS VARCHAR(30));

SELECT PNAME,COUNT(PNAME)FROM ORDERS GROUP BY PNAME HAVING
COUNT(PNAME)>50;

SELECT DISTINCT ORDERS.UNAME,ORDERS.OID, ORDER_DETAILS.ODATE FROM
ORDERS JOIN ORDER_DETAILS ON ORDERS.OID=ORDER_DETAILS.OID ORDER BY
ODATE DESC;

SELECT SUM(PRICE*QUANTITY)FROM ORDERS;

CREATE TABLE SALES(PID VARCHAR(10) REFERENCES PRODUCTS(PID)
,QUANTITY_SOLD INTEGER ,DATE_SOLD DATE);SELECT MONTH(DATE_SOLD),PID,SUM(QUANTITY_SOLD) FROM SALES GROUP BY
PID ,MONTH(DATE_SOLD) HAVING COUNT(MONTH(DATE_SOLD)) <=3 ORDER BY
MONTH(DATE_SOLD) ASC ;

SELECT PNAME FROM PRODUCTS WHERE PID IN(SELECT PID FROM ORDERS);SELECT PNAME FROM ORDERS WHERE EXISTS (SELECT PID FROM PRODUCTS);